#!/bin/bash
# Script para configurar GitHub Actions secrets
# Execute este script após criar o repositório no GitHub

echo "=== Configuração do GitHub Actions ==="
echo ""
echo "PASSO 1: Gere um GitHub Personal Access Token"
echo "   1. Acesse: https://github.com/settings/tokens"
echo "   2. Clique: Generate new token (classic)"
echo "   3. Selecione scopes:"
echo "      - repo (full control)"
echo "      - workflow"
echo "   4. Copie o token gerado"
echo ""
echo "PASSO 2: Configure oRemote com o token"
echo "   git remote set-url origin https://SEU_TOKEN@github.com/USUARIO/guardia-app.git"
echo ""
echo "PASSO 3: Adicione Secrets no GitHub (via UI)"
echo "   Acesse: https://github.com/USUARIO/guardia-app/settings/secrets/actions"
echo "   Adicione:"
echo "   - AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
echo "   - AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
echo "   - AWS_ACCOUNT_ID: 026544697783"
echo "   - EC2_DEV_INSTANCE_ID: (ID da instância EC2 dev)"
echo "   - EC2_TEST_INSTANCE_ID: (ID da instância EC2 test)"
echo "   - EC2_PROD_INSTANCE_ID: (ID da instância EC2 prod)"
echo ""
echo "PASSO 4: Configure as branches"
echo "   - main: produção"
echo "   - test: homologação"
echo "   - develop: desenvolvimento"
echo ""
echo "PASSO 5: Execute o push inicial"
echo "   git checkout -b develop"
echo "   git push -u origin develop"

# Exibir as chaves para o usuário configurar manualmente
echo ""
echo "=== Suas chaves atuais ==="
echo "AWS Access Key ID: AKIAQMLRP6G37L5R7JU5"
echo "AWS Account ID: 026544697783"
echo "AWS Region: us-east-1"