#!/bin/bash
# Script para configurar o Retool com o dashboard CI/CD
# Como o Retool Cloud Free não permite criação via API,
# este script gera o JSON que você pode importar manualmente

RETOOL_SUBDOMAIN="retool_01kpbqncmtsjm95javczj95a2w"
EC2_IP="44.222.98.180"

echo "=== Configuração do Retool ==="
echo ""
echo "1. Acesse: https://$RETOOL_SUBDOMAIN.retool.com"
echo "2. Crie um novo App chamado 'Guardia CI/CD Pipeline'"
echo "3. Adicione os seguintes componentes:"
echo ""
echo "   Stats Components:"
echo "   - DEV: http://$EC2_IP:3000"
echo "   - TEST: http://$EC2_IP:3001"
echo "   - PROD: http://$EC2_IP:3002"
echo ""
echo "   Buttons:"
echo "   - Deploy DEV (trigger: develop branch)"
echo "   - Deploy TEST (trigger: test branch)"
echo "   - Deploy PROD (trigger: main branch)"
echo ""
echo "4. Adicione uma Table para histórico de deploys"
echo ""
echo "5. Crie um Workflow com Webhook trigger"
echo "   - Copie a URL do webhook"
echo "   - Adicione como secret no GitHub: RETOOL_WEBHOOK_URL"
echo ""
echo "=== Recursos para adicionar ==="
echo ""
echo "Resource 1: AWS Secrets Manager"
echo "  - Region: us-east-1"
echo "  - Access Key: AKIAQMLRP6G37L5R7JU5"
echo ""
echo "Resource 2: GitHub API"
echo "  - URL: https://api.github.com"
echo "  - Auth: Bearer Token"
echo ""
echo "Resource 3: EC2 Guardia"
echo "  - URL: http://$EC2_IP"
echo ""
echo "=== Pronto! ==="
echo "O dashboard mostrará:"
echo "  - Status dos 3 ambientes (dev/test/prod)"
echo "  - Botões para deploy manual"
echo "  - Histórico de deploys"
echo "  - Logs de execução"